version: '2'
services:
  led_manager:
    image: jengalamp_led_manager
    privileged: true
    environment:
      - LEDSERVICE_HOST=localhost
      - LEDSERVICE_PORT=9000
    expose:
      - "9000"
    networks:
      - botnet
  tbot:
    image: jengalamp_tbot
    env_file:
      - ~/.env
    networks:
      - botnet
networks:
  botnet:
    external: true