version: '2'
services:
  led_manager:
    image: jengalamp_led_manager
    privileged: true
    environment:
      - LEDSERVICE_HOST=localhost
      - LEDSERVICE_PORT=9000
    volume:
      - ~/jengalamp/led_manager:/app
  tbot:
    image: jengalamp_tbot
    env_file:
      - ~/.env
    volume:
      - ~/jengalamp/tbot:/bot
