version: '2'
services:
  led_manager:
    image: jengalamp_led_manager
    container_name: led_manager
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - ~/led_manager.env
    ports:
      - "9000:9000"
    expose:
      - "9000"
    networks:
      - botnet
  tbot:
    image: jengalamp_tbot
    container_name: tbot
    env_file:
      - ~/.env
    networks:
      - botnet
networks:
  botnet:
    external: true